### ISSUE TITLE
Customer is not being returned to Prestashop 1.6.1.4

### ISSUE THREAD

**Issue by nssimpson** [Paymentsense-DevSupport/Prestashop#1]
Hi Ryan, I thought I should post the issue here in case others have noticed this same issue...

We've installed the latest module, which says it's for Prestashop 1.6.1.4. We're cleared the cache, rebooted the server, opened up port 4430 and checked server logs but can't find anything wrong at our end.

Customers are being directed to PaymentSense and can pay successfully.

Problem is the customer is not redirected to Prestashop so has no option but to close or press the back button on the browser.

The order is not completed within Prestashop.

**Comment by nssimpson** [comment]
I've found the issue and it's due to the paymentsense.php file only being configured to work with Prestashop sites set to use HTTP instead of HTTPS. Two fix for HTTPS sites lines 172 and 318 need changing to:
$image_url = 'https://'.$_SERVER['HTTP_HOST'].__PS_BASE_URI__.'modules/'.$this->name.'/img/';
$module_url = 'https://'.$_SERVER['HTTP_HOST'].__PS_BASE_URI__.'modules/paymentsense/';

Would be good if the module was able to automatically detect HTTP and HTTPS sites.

Also the hyperlink at line 235 needs fixing so it reads:
<tr><td colspan="2" style="padding-bottom:10px; font-size:16px;">'.$this->l('Enter your gateway merchant details below and click save to begin taking payments.').'Please check your gateway details <a href="https://www.psdevsupport.co.uk/CheckDetails/" target="_blank"><strong>HERE</strong></a> first.</td></tr>

**Comment by Ryan-Odonnell** [comment]
This was an environment specific fix. The issue stemmed from users server security settings.

**Comment by nssimpson** [comment]
Sorry to disagree but the issue stems from the URL redirect in your code being hard set to HTTP even when the site enforces HTTPS. It appears that if the server settings don't allow unsecure HTTP connections to be redirected to HTTPS then the module fails unless the user manually edits your code as per my previous post. It would be nice if you edited the code to make it point to HTTPS automatically if the site uses HTTPS since this seems like a very easy fix.

Although your default code works on your test HTTPS environment I can confirm that doing a SSLLabs test on your site shows that it only gets a C security rating whereas we get an A. I know that many live production sites fail to close security holes so don't get A ratings so I'm sure your module will work for them but it's not really the right approach in my opinion. I'd like to ask if you could please improve the security of your test site to hit A (or even A+, which we decided against due to excessive restrictions) and retest.

Cheers

**Comment by Ryan-Odonnell** [comment]
Hi nssimpson,

Please continue this discussion by replying to the support request you generated previously.

Thanks
